package modal;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
* Bus generated by hbm2java
*/
public class Bus  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
private String id;
  private String name;
  private String type;
  private String start;
  private String dest;
  private Date departure;
  private Date arrival;
  private int noSeats;
  private String description;
  private Set<Ticket> tickets = new HashSet<>(0);

 public Bus() {
 }

	
 public Bus(String id, int noSeats) {
     this.id = id;
     this.noSeats = noSeats;
 }
 public Bus(String id, String name, String type, String start, String dest, Date departure, Date arrival, int noSeats, String description) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.start = start;
    this.dest = dest;
    this.departure = departure;
    this.arrival = arrival;
    this.noSeats = noSeats;
    this.description = description;
 }

 public String getId() {
     return this.id;
 }
 
 public void setId(String id) {
     this.id = id;
 }
 public String getName() {
     return this.name;
 }
 
 public void setName(String name) {
     this.name = name;
 }
 public String getType() {
     return this.type;
 }
 
 public void setType(String type) {
     this.type = type;
 }
 public String getStart() {
     return this.start;
 }
 
 public void setStart(String start) {
     this.start = start;
 }
 public String getDest() {
     return this.dest;
 }
 
 public void setDest(String dest) {
     this.dest = dest;
 }
 public Date getDeparture() {
     return this.departure;
 }
 
 public void setDeparture(Date departure) {
     this.departure = departure;
 }
 public Date getArrival() {
     return this.arrival;
 }
 
 public void setArrival(Date arrival) {
     this.arrival = arrival;
 }
 public int getNoSeats() {
     return this.noSeats;
 }
 
 public void setNoSeats(int noSeats) {
     this.noSeats = noSeats;
 }
 public String getDescription() {
     return this.description;
 }
 
 public void setDescription(String description) {
     this.description = description;
 }
 public Set<Ticket> getTickets() {
     return this.tickets;
 }
 
 public void setTickets(Set<Ticket> tickets) {
     this.tickets = tickets;
 }

}


