package modal;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private String userName;
     private String password;
     private String name;
     private String email;
     private Set<Ticket> tickets = new HashSet<>(0);

    public User() {
    }

	
    public User(String userName) {
        this.userName = userName;
    }
    public User(String userName, String password, String name, String email) {
       this.userName = userName;
       this.password = password;
       this.name = name;
       this.email = email;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}
